<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xml [
<!ELEMENT xml (Thread*)>
<!ATTLIST xml 
version CDATA #REQUIRED
>
<!ELEMENT Thread (RelQuestion, RelComment*)>
<!ATTLIST Thread
 THREAD_SEQUENCE CDATA #REQUIRED
>
<!ELEMENT RelQuestion (RelQSubject, RelQBody, RelQClean)>
<!ATTLIST RelQuestion
RELQ_ID CDATA #REQUIRED
RELQ_CATEGORY CDATA #REQUIRED
RELQ_DATE CDATA #REQUIRED
RELQ_USERID CDATA #REQUIRED
RELQ_USERNAME CDATA #REQUIRED
>
<!ELEMENT RelQSubject (#PCDATA)>
<!ELEMENT RelQBody (#PCDATA)>
<!ELEMENT RelQClean (#PCDATA)>
<!ELEMENT RelComment (RelCBody, RelCClean)>
<!ATTLIST RelComment
RELC_ID CDATA #REQUIRED
RELC_DATE CDATA #REQUIRED
RELC_USERID CDATA #REQUIRED
RELC_USERNAME CDATA #REQUIRED
RELC_RELEVANCE2RELQ CDATA #REQUIRED
>
<!ELEMENT RelCBody (#PCDATA)>
<!ELEMENT RelCClean (#PCDATA)>
]>
<xml version="1.0">

	<Thread THREAD_SEQUENCE="Q201_R26">
		<RelQuestion RELQ_ID="Q201_R26" RELQ_CATEGORY="Working in Qatar" RELQ_DATE="2015-01-07 10:00:25" RELQ_USERID="U4433" RELQ_USERNAME="komail">
			<RelQSubject>Salary vs Cost of Living Doha</RelQSubject>
			<RelQBody>&amp;lt;p&amp;gt;Family with 2 kids (9 &amp;amp; 5 years old) - both school going&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;Salary package of 20K (with no other benefit)&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;Is it a good deal?&amp;lt;/p&amp;gt;</RelQBody>
			<RelQClean>Salary vs Cost of Living Doha // Family with 2 kids (9 &amp; 5 years old) - both school going Salary package of 20K (with no other benefit) Is it a good deal?</RelQClean>
		</RelQuestion>

		<RelComment RELC_ID="Q201_R26_C1" RELC_DATE="2015-01-07 10:31:45" RELC_USERID="U4434" RELC_USERNAME="aamirjaved" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>For family with 2 child, you ll probably need 2BR flat which will cost about 7000-8000 and for schooling you ll probably need 4000-5000. so it means these two will take major chunk of your salary. Further you can take 3000 monthly living expense and 2000 for conveyance. Additionally any medical requirements. Now its upto you to decide...</RelCBody>
			<RelCClean>For family with 2 child; you ll probably need 2BR flat which will cost about 7000-8000 and for schooling you ll probably need 4000-5000. so it means these two will take major chunk of your salary. Further you can take 3000 monthly living expense and 2000 for conveyance. Additionally any medical requirements. Now its upto you to decide...</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C2" RELC_DATE="2015-01-07 10:43:17" RELC_USERID="U640" RELC_USERNAME="acchabaccha" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>Aamirjaved's calculation is somewhat on the high side. I believe you should be able to get a 2BR within QR 5000 and also you can easily manage your monthly expenses within QR 2000. For the schooling, if you are an Asian, it is not that costly to my understanding. As such, my view is that if you are an Asian, grab the offer; but if you are a westerner, kick it. </RelCBody>
			<RelCClean>Aamirjaved's calculation is somewhat on the high side. I believe you should be able to get a 2BR within QR 5000 and also you can easily manage your monthly expenses within QR 2000. For the schooling; if you are an Asian; it is not that costly to my understanding. As such; my view is that if you are an Asian; grab the offer; but if you are a westerner; kick it.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C3" RELC_DATE="2015-01-07 10:44:34" RELC_USERID="U4435" RELC_USERNAME="arkb" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCBody>We can't say if it's a good deal - you don't include details of the role.


Try to get schooling included in the package.


Agree with aamirjaved. Depends on what standard of living you want. Depending on area, you may need 10k+ for a nice 2 bed.</RelCBody>
			<RelCClean>We can't say if it's a good deal - you don't include details of the role. Try to get schooling included in the package. Agree with aamirjaved. Depends on what standard of living you want. Depending on area; you may need 10k+ for a nice 2 bed.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C4" RELC_DATE="2015-01-07 10:49:36" RELC_USERID="U4436" RELC_USERNAME="Viswakumar" RELC_RELEVANCE2RELQ="Bad">
			<RelCBody>Agree with aamirjaved.</RelCBody>
			<RelCClean>Agree with aamirjaved.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C5" RELC_DATE="2015-01-07 11:19:50" RELC_USERID="U4437" RELC_USERNAME="BISHWANATH2014" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>EZDAN 2 bedroom Fully Furnished you get in QR 5500, School Asian with Transportation for 2 kids 750 x2 = 1500 and QR 3000 living expense and QR 1000 miscellaneous.

So Net Savings QR 9000 as of my 10 years experience in Doha living with Family.</RelCBody>
			<RelCClean>EZDAN 2 bedroom Fully Furnished you get in QR 5500; School Asian with Transportation for 2 kids 750 x2 = 1500 and QR 3000 living expense and QR 1000 miscellaneous. So Net Savings QR 9000 as of my 10 years experience in Doha living with Family.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C6" RELC_DATE="2015-01-07 11:55:01" RELC_USERID="U4438" RELC_USERNAME="mido-doha" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCBody>no enough for the near future as Qatar is getting more expensive not yearly! you can feel it every 4-5 months.</RelCBody>
			<RelCClean>no enough for the near future as Qatar is getting more expensive not yearly! you can feel it every 4-5 months.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C7" RELC_DATE="2015-01-07 11:58:07" RELC_USERID="U4439" RELC_USERNAME="krohit_in" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCBody>I will suggest to go for unfurnished property, it will cost you around QR 4000-4800 depends on locality, Asian school with transportation for two kids 1000 X2= QR 2000, QR 2000 for living expense and QR 500 for transport, Total cost of living would be QR 8500 - 9300, You can save QR +10500, But it totally depends on your living standard.  </RelCBody>
			<RelCClean>I will suggest to go for unfurnished property; it will cost you around QR 4000-4800 depends on locality; Asian school with transportation for two kids 1000 X2= QR 2000; QR 2000 for living expense and QR 500 for transport; Total cost of living would be QR 8500 - 9300; You can save QR +10500; But it totally depends on your living standard.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C8" RELC_DATE="2015-01-07 12:08:47" RELC_USERID="U4440" RELC_USERNAME="Hamidpipi1" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCBody>1.2BHK - QR 5000/PM
2.Furniture Allowance Incl All house hold items (For one time = QR 14000 - 16000) for two bed room flat.
Schooling for tow kids incl transport (Asian) = QR 1800
3.Net + Phone = QR 600

4. House living Expenses = QR 2500
5. Miscellaneous = QR 1000

if you are from India then the cost of living should be like Allmost the same.....
</RelCBody>
			<RelCClean>1.2BHK - QR 5000/PM 2.Furniture Allowance Incl All house hold items (For one time = QR 14000 - 16000) for two bed room flat. Schooling for tow kids incl transport (Asian) = QR 1800 3.Net + Phone = QR 600 4. House living Expenses = QR 2500 5. Miscellaneous = QR 1000 if you are from India then the cost of living should be like Allmost the same.....</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C9" RELC_DATE="2015-01-07 12:43:13" RELC_USERID="U68" RELC_USERNAME="Mary-vani" RELC_RELEVANCE2RELQ="Bad">
			<RelCBody>if you have decided to join this Qatar company, you mus to attested your educational certificate.For attestation &amp;amp; translation purpose please contact to sheenservices wll.. website:http://sheenservices.com/contact-us.html-44366147/55974495</RelCBody>
			<RelCClean>if you have decided to join this Qatar company; you mus to attested your educational certificate.For attestation &amp; translation purpose please contact to sheenservices wll.. website:http://sheenservices.com/contact-us.html-44366147/55974495</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C10" RELC_DATE="2015-01-07 13:47:59" RELC_USERID="U4124" RELC_USERNAME="yacine.h" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCBody>If you are Asian you should be fine with it. If you are European you wouldn't be fine with it all as the schools and the rent fees will eat up much of it</RelCBody>
			<RelCClean>If you are Asian you should be fine with it. If you are European you wouldn't be fine with it all as the schools and the rent fees will eat up much of it</RelCClean>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q201_R29">
		<RelQuestion RELQ_ID="Q201_R29" RELQ_CATEGORY="Doha Shopping" RELQ_DATE="2011-01-24 22:32:54" RELQ_USERID="U4441" RELQ_USERNAME="sakib12345">
			<RelQSubject>Why to DSLR cams cost more in Qatar ?</RelQSubject>
			<RelQBody>i see that the prices are higher in Qatar on DSLR cams ? why is it? can any one suggest how i can by cheaper online. i dont have any experience buying things online. so i need advices :)</RelQBody>
			<RelQClean>Why to DSLR cams cost more in Qatar ? // i see that the prices are higher in Qatar on DSLR cams ? why is it? can any one suggest how i can by cheaper online. i dont have any experience buying things online. so i need advices :)</RelQClean>
		</RelQuestion>

		<RelComment RELC_ID="Q201_R29_C1" RELC_DATE="2011-01-24 22:39:19" RELC_USERID="U643" RELC_USERNAME="lamea" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCBody>every thing is expensive here.</RelCBody>
			<RelCClean>every thing is expensive here.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C2" RELC_DATE="2011-01-24 22:39:44" RELC_USERID="U578" RELC_USERNAME="flexicode" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCBody>better stay away from online purchases, especially if you want it to be delivered on a qatar address, that too a digicam...DSLR prices are higher in qatar as compared to where?</RelCBody>
			<RelCClean>better stay away from online purchases; especially if you want it to be delivered on a qatar address; that too a digicam...DSLR prices are higher in qatar as compared to where?</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C3" RELC_DATE="2011-01-24 22:45:42" RELC_USERID="U4441" RELC_USERNAME="sakib12345" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>on amazon.com it says Canon EOS Rebel T1i 15.1 MP CMOS Digital SLR Camera with 3-Inch LCD and EF-S 18-55mm f/3.5-5.6 IS Lens @ $589.99 :|</RelCBody>
			<RelCClean>on amazon.com it says Canon EOS Rebel T1i 15.1 MP CMOS Digital SLR Camera with 3-Inch LCD and EF-S 18-55mm f/3.5-5.6 IS Lens @ $589.99 :|</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C4" RELC_DATE="2011-01-24 22:55:49" RELC_USERID="U4441" RELC_USERNAME="sakib12345" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCBody>Canon EOS Rebel T1i (canon 500D) in Qatar is Qr.2998 which is around $821............</RelCBody>
			<RelCClean>Canon EOS Rebel T1i (canon 500D) in Qatar is Qr.2998 which is around $821............</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C5" RELC_DATE="2011-01-24 22:55:57" RELC_USERID="U578" RELC_USERNAME="flexicode" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCBody>you can get this for about the same price (around 2000 QR) here as well but you need to check at 3 - 4 places for a comparison. there is an undefinable difference in prices even on major brands here in qatar...</RelCBody>
			<RelCClean>you can get this for about the same price (around 2000 QR) here as well but you need to check at 3 - 4 places for a comparison. there is an undefinable difference in prices even on major brands here in qatar...</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C6" RELC_DATE="2011-01-24 22:59:34" RELC_USERID="U4441" RELC_USERNAME="sakib12345" RELC_RELEVANCE2RELQ="Bad">
			<RelCBody>i checked lulu &amp;amp; carrefour and the prices i found are Qr.2999 &amp;amp; 2998......... where do i find it @ Qr.2000 here?</RelCBody>
			<RelCClean>i checked lulu &amp; carrefour and the prices i found are Qr.2999 &amp; 2998......... where do i find it @ Qr.2000 here?</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C7" RELC_DATE="2011-01-24 23:07:08" RELC_USERID="U4442" RELC_USERNAME="omar1733" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>Because there are not too much specialty stores that caters only professional cameras (DSLRs). Mostly camera stores can be found only in malls but they are not specialty stores. You know how mall owners jack-up prices of goods, especially if it comes or imported outside Doha. If you have friends in UAE, you can ask them to buy you one and just shipped it you. Or, there are some people selling DLSRs here in QL. You can search the classified ad here.</RelCBody>
			<RelCClean>Because there are not too much specialty stores that caters only professional cameras (DSLRs). Mostly camera stores can be found only in malls but they are not specialty stores. You know how mall owners jack-up prices of goods; especially if it comes or imported outside Doha. If you have friends in UAE; you can ask them to buy you one and just shipped it you. Or; there are some people selling DLSRs here in QL. You can search the classified ad here.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C8" RELC_DATE="2011-01-24 23:12:04" RELC_USERID="U4441" RELC_USERNAME="sakib12345" RELC_RELEVANCE2RELQ="Bad">
			<RelCBody>omar1733 @ thanx mate...i'll check :)</RelCBody>
			<RelCClean>omar1733 @ thanx mate...i'll check :)</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C9" RELC_DATE="2011-01-24 23:13:17" RELC_USERID="U4442" RELC_USERNAME="omar1733" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>You can try Gulf Foto in Musheirib area.</RelCBody>
			<RelCClean>You can try Gulf Foto in Musheirib area.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C10" RELC_DATE="2011-01-25 00:52:27" RELC_USERID="U1304" RELC_USERNAME="cdpascual" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>you can try b&amp;amp;h which is a trusted one, they can ship here.OR if you know somebody in US or travelling there you can ask them to buy it for you. that's what i did. my friend had ordered too from some sellers in ebay, mostly D90.</RelCBody>
			<RelCClean>you can try b&amp;h which is a trusted one; they can ship here.OR if you know somebody in US or travelling there you can ask them to buy it for you. that's what i did. my friend had ordered too from some sellers in ebay; mostly D90.</RelCClean>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q201_R35">
		<RelQuestion RELQ_ID="Q201_R35" RELQ_CATEGORY="Welcome to Qatar" RELQ_DATE="2011-07-04 21:01:10" RELQ_USERID="U4443" RELQ_USERNAME="newtodoha2011">
			<RelQSubject>got a job offer of 12000 QR. whats its worth?</RelQSubject>
			<RelQBody>&amp;lt;P&amp;gt;Hi, I am working currently in dubai and i hav been offered a job with a salary of 12000 QR (inclusive of basic, hra and transportation). You have to get your own place and car. I would like to know how much a single BHK would cost and also how much utilities bills would come to for a month?how costly is it to have food from restaurants as i do not know how to cook. can some one provide an insight please. Thank you.&amp;lt;/P&amp;gt;</RelQBody>
			<RelQClean>got a job offer of 12000 QR. whats its worth? // Hi; I am working currently in dubai and i hav been offered a job with a salary of 12000 QR (inclusive of basic; hra and transportation). You have to get your own place and car. I would like to know how much a single BHK would cost and also how much utilities bills would come to for a month?how costly is it to have food from restaurants as i do not know how to cook. can some one provide an insight please. Thank you.</RelQClean>
		</RelQuestion>

		<RelComment RELC_ID="Q201_R35_C1" RELC_DATE="2011-07-04 21:08:22" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="Bad">
			<RelCBody>&amp;lt;P&amp;gt;Which company dude??&amp;lt;/P&amp;gt;</RelCBody>
			<RelCClean>Which company dude??</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R35_C2" RELC_DATE="2011-07-04 21:23:26" RELC_USERID="U4443" RELC_USERNAME="newtodoha2011" RELC_RELEVANCE2RELQ="Bad">
			<RelCBody>&amp;lt;P&amp;gt;HI &amp;lt;A title=&amp;quot;View user profile.&amp;quot; href=&amp;quot;http://www.qatarliving.com/user/arshad124&amp;quot;&amp;gt;arshad124&amp;lt;/A&amp;gt;&amp;amp;nbsp;, sorry but i cant reveal the company details...whts ur opinion? is 12k good enough?&amp;lt;/P&amp;gt;</RelCBody>
			<RelCClean>HI arshad124 ; sorry but i cant reveal the company details...whts ur opinion? is 12k good enough?</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R35_C3" RELC_DATE="2011-07-04 21:41:01" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="Bad">
			<RelCBody>&amp;lt;P&amp;gt;hmmm, depends on which company you know : /&amp;lt;/P&amp;gt;</RelCBody>
			<RelCClean>hmmm; depends on which company you know : /</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R35_C4" RELC_DATE="2011-07-04 21:42:00" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="Bad">
			<RelCBody>&amp;lt;P&amp;gt;Seriously message me the company atleast....&amp;lt;/P&amp;gt;</RelCBody>
			<RelCClean>Seriously message me the company atleast....</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R35_C5" RELC_DATE="2011-07-04 21:42:30" RELC_USERID="U74" RELC_USERNAME="FlyingAce" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>&amp;lt;p&amp;gt;Firstly it depends on your Life Style, and then If you are getting more then 12000QAR, in Dubai then better off to stay there...&amp;amp;nbsp;&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;The desicion is all yours...&amp;amp;nbsp;&amp;lt;/p&amp;gt;</RelCBody>
			<RelCClean>Firstly it depends on your Life Style; and then If you are getting more then 12000QAR; in Dubai then better off to stay there... The desicion is all yours...</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R35_C6" RELC_DATE="2011-07-04 21:47:49" RELC_USERID="U4444" RELC_USERNAME="qatartalks" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>&amp;lt;P&amp;gt;well the salary seem to be good, but if you are bring your family then house of 2BK without furnish and good lcoation would not cost you less then 4000 qr. then furnuiture and basic requirement that shall shoot upto 10K. So indirect 5k per month would be the rent. then car if you go for high end car apprx starting from 100000 to 123000 then monthy EMI would be between 4000 to 4500. then food and other expensies..Now it is totallly depend on how you spend it dude.&amp;lt;/P&amp;gt;
&amp;lt;P&amp;gt;According to me it good salary. But spend wisely and save for your further.&amp;lt;/P&amp;gt;
&amp;lt;P&amp;gt;&amp;amp;nbsp;&amp;lt;/P&amp;gt;</RelCBody>
			<RelCClean>well the salary seem to be good; but if you are bring your family then house of 2BK without furnish and good lcoation would not cost you less then 4000 qr. then furnuiture and basic requirement that shall shoot upto 10K. So indirect 5k per month would be the rent. then car if you go for high end car apprx starting from 100000 to 123000 then monthy EMI would be between 4000 to 4500. then food and other expensies..Now it is totallly depend on how you spend it dude. According to me it good salary. But spend wisely and save for your further.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R35_C7" RELC_DATE="2011-07-04 21:54:08" RELC_USERID="U4443" RELC_USERNAME="newtodoha2011" RELC_RELEVANCE2RELQ="Bad">
			<RelCBody>&amp;lt;P&amp;gt;@&amp;lt;A title=&amp;quot;View user profile.&amp;quot; href=&amp;quot;http://www.qatarliving.com/user/arshad124&amp;quot;&amp;gt;arshad124&amp;lt;/A&amp;gt;&amp;amp;nbsp;mate sorry again but i cant mention it....and whts the company name got to do with this salary?&amp;lt;/P&amp;gt;
&amp;lt;P&amp;gt;@flyingace: i make arround 9K here in dubai...this job pays more but i hav heard its quite costly there...my lifesytle is more or less simple.&amp;lt;/P&amp;gt;
&amp;lt;P&amp;gt;i pay arround&amp;amp;nbsp; 1500 for a studio here..so how much would a studio cost there? the place is called wakrah i think..wht abt utilitiy bills and hotel expenses?&amp;lt;/P&amp;gt;
&amp;lt;P&amp;gt;thanks again for your reply.&amp;lt;/P&amp;gt;
&amp;lt;P&amp;gt;&amp;amp;nbsp;&amp;lt;/P&amp;gt;
&amp;lt;P&amp;gt;&amp;amp;nbsp;&amp;lt;/P&amp;gt;</RelCBody>
			<RelCClean>@ arshad124 mate sorry again but i cant mention it....and whts the company name got to do with this salary? @flyingace: i make arround 9K here in dubai...this job pays more but i hav heard its quite costly there...my lifesytle is more or less simple. i pa</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R35_C8" RELC_DATE="2011-07-04 22:00:42" RELC_USERID="U4443" RELC_USERNAME="newtodoha2011" RELC_RELEVANCE2RELQ="Bad">
			<RelCBody>&amp;lt;P&amp;gt;hi &amp;lt;A title=&amp;quot;View user profile.&amp;quot; href=&amp;quot;http://www.qatarliving.com/user/qatartalks&amp;quot;&amp;gt;qatartalks&amp;lt;/A&amp;gt;,&amp;lt;/P&amp;gt;
&amp;lt;P&amp;gt;well i am a bachelor for now and no plan to get married soon.also i plan to export my car from dubai to doha...how much does a decent studio cost at wakrah? savings is important to me and also i will need tht for a future family life..so with 12k salary&amp;amp;nbsp; would like to calculate wht my expenses would be...thanx for the support...&amp;lt;/P&amp;gt;</RelCBody>
			<RelCClean>hi qatartalks ; well i am a bachelor for now and no plan to get married soon.also i plan to export my car from dubai to doha...how much does a decent studio cost at wakrah? savings is important to me and also i will need tht for a future family life..so with 12k salary would like to calculate wht my expenses would be...thanx for the support...</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R35_C9" RELC_DATE="2011-07-04 22:02:43" RELC_USERID="U4445" RELC_USERNAME="zuzo" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCBody>&amp;lt;p&amp;gt;not worth the change for just 3000 extra. nothing compared to Dubai... here things are not that economical as opposed to the thought... i was in Dubai.. and i believe that Dubai is now much better, as compared to what it used to be.. but again.. compare the prospects when u change the job, what are the growth prospects... keep bear in mind.. the cost of living is going to increase... and rate of inflation will be much higher than dubai..&amp;lt;/p&amp;gt;</RelCBody>
			<RelCClean>not worth the change for just 3000 extra. nothing compared to Dubai... here things are not that economical as opposed to the thought... i was in Dubai.. and i believe that Dubai is now much better; as compared to what it used to be.. but again.. compare the prospects when u change the job; what are the growth prospects... keep bear in mind.. the cost of living is going to increase... and rate of inflation will be much higher than dubai..</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R35_C10" RELC_DATE="2011-07-04 22:08:52" RELC_USERID="U4443" RELC_USERNAME="newtodoha2011" RELC_RELEVANCE2RELQ="Bad">
			<RelCBody>&amp;lt;P&amp;gt;HI zuzo, well the growth prospects later on for me would be better. as of now i am changing my line of work..if i set a target of 2 years in doha and then head back to dubai then i myt have a better growth when i get back here...thank u for that honest comment...i still have 2 weeks to decide. Dubai is good, but chances of landing in a good job is less now.i have been here for 3 years and the market is not good as it used to be...but inflation in qatar i agree myt be higher..if i was aiming at just 2 years, whts your opinion?&amp;lt;/P&amp;gt;</RelCBody>
			<RelCClean>HI zuzo; well the growth prospects later on for me would be better. as of now i am changing my line of work..if i set a target of 2 years in doha and then head back to dubai then i myt have a better growth when i get back here...thank u for that honest comment...i still have 2 weeks to decide. Dubai is good; but chances of landing in a good job is less now.i have been here for 3 years and the market is not good as it used to be...but inflation in qatar i agree myt be higher..if i was aiming at just 2 years; whts your opinion?</RelCClean>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q201_R41">
		<RelQuestion RELQ_ID="Q201_R41" RELQ_CATEGORY="Salary and Allowances" RELQ_DATE="2011-05-25 06:09:00" RELQ_USERID="U4446" RELQ_USERNAME="bioless">
			<RelQSubject>Is 30000 QAR good enough salary for a couple to move to Qatar?</RelQSubject>
			<RelQBody>Moving to Qatar soon, have received an offer of QAR 30K, is that good enough for a couple to be in Qatar? We have No kids.  </RelQBody>
			<RelQClean>Is 30000 QAR good enough salary for a couple to move to Qatar? // Moving to Qatar soon; have received an offer of QAR 30K; is that good enough for a couple to be in Qatar? We have No kids.</RelQClean>
		</RelQuestion>

		<RelComment RELC_ID="Q201_R41_C1" RELC_DATE="2011-05-25 06:42:55" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>That's good offer...Welcome to Qatar...:-)</RelCBody>
			<RelCClean>That's good offer...Welcome to Qatar...:-)</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R41_C2" RELC_DATE="2011-05-25 06:46:05" RELC_USERID="U308" RELC_USERNAME="tryke" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>I am receiving less than that and i have moved to Qatar with wife and 3 kids and yet somehow we managed to survive... Surely 30K QR will be more than good enough for you and your wife to live and enjoy life in Doha...</RelCBody>
			<RelCClean>I am receiving less than that and i have moved to Qatar with wife and 3 kids and yet somehow we managed to survive... Surely 30K QR will be more than good enough for you and your wife to live and enjoy life in Doha...</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R41_C3" RELC_DATE="2011-05-25 06:49:26" RELC_USERID="U308" RELC_USERNAME="tryke" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>I am receiving less than that and i have moved to Qatar with my wife and 3 kids and yet somehow we managed to survive... Surely 30K QR will be more than good enough for you and your wife to live and enjoy life in Doha...
</RelCBody>
			<RelCClean>I am receiving less than that and i have moved to Qatar with my wife and 3 kids and yet somehow we managed to survive... Surely 30K QR will be more than good enough for you and your wife to live and enjoy life in Doha...</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R41_C4" RELC_DATE="2011-05-25 07:18:31" RELC_USERID="U134" RELC_USERNAME="timebandit" RELC_RELEVANCE2RELQ="Bad">
			<RelCBody>Oh come on... are you stupid or what. That is good money and you know it. If you  can't figure out if that is a good enough salary then you don't deserve that amount.</RelCBody>
			<RelCClean>Oh come on... are you stupid or what. That is good money and you know it. If you can't figure out if that is a good enough salary then you don't deserve that amount.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R41_C5" RELC_DATE="2011-05-25 07:20:49" RELC_USERID="U4238" RELC_USERNAME="samiko" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>It depends on your living standard and expectation for savings. In this connection it is important to know do all allowances (specialy accomodation allowance) are included or not in this amount. For example rent of a villa will be in the range of 12,000 - 20,000 QR etc.
Good Luck</RelCBody>
			<RelCClean>It depends on your living standard and expectation for savings. In this connection it is important to know do all allowances (specialy accomodation allowance) are included or not in this amount. For example rent of a villa will be in the range of 12;000 - 20;000 QR etc. Good Luck</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R41_C6" RELC_DATE="2011-05-25 07:26:39" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCBody>DO YOU THINK THAT YOU WILL EARN THAT AMOUNT IN YOUR COUNTRY????CMON......AND HOW COME A LOT OF EXPATS ARE COMING TO WORK INSTEAD IN THEIR HOME COUNTRY?????DONT BE SO SILLY....</RelCBody>
			<RelCClean>DO YOU THINK THAT YOU WILL EARN THAT AMOUNT IN YOUR COUNTRY????CMON......AND HOW COME A LOT OF EXPATS ARE COMING TO WORK INSTEAD IN THEIR HOME COUNTRY?????DONT BE SO SILLY....</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R41_C7" RELC_DATE="2011-05-25 07:28:24" RELC_USERID="U4447" RELC_USERNAME="Al-Khor" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>it depends

if it is excluding the accomodation or including

because if you want to live in a villa


you need something like 10000 QR monthly

and if it it is included then you will end up with 20000

which is enough to live a meduam life for you and your family


To be honst i think it is a good salary for an engineer or maybe senior person


so go a head and good luck</RelCBody>
			<RelCClean>it depends if it is excluding the accomodation or including because if you want to live in a villa you need something like 10000 QR monthly and if it it is included then you will end up with 20000 which is enough to live a meduam life for you and your family To be honst i think it is a good salary for an engineer or maybe senior person so go a head and good luck</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q201_R41_C8" RELC_DATE="2011-05-25 07:33:33" RELC_USERID="U561" RELC_USERNAME="bral1960" RELC_RELEVANCE2RELQ="Good">
			<RelCBody>Depend which one is your life-style? Is the accommodation paid by Company? and the car (3000 for rent)? Do you like compound villa (12000) or apartment (7000)? Do you like club (500 per month)? Do you like drink alcohol (500 per month)? Do you like go to restaurant (700 per month)? Your wife like new clothes (1000 per month)? QR 30.000 are not enough for western couple!

</RelCBody>