<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xml [
<!ELEMENT xml (OrgQuestion*)>
<!ATTLIST xml 
version CDATA #REQUIRED
>
<!ELEMENT Thread (RelQuestion, RelComment*)>
<!ATTLIST Thread
 THREAD_SEQUENCE CDATA #REQUIRED
>
<!ELEMENT RelQuestion (RelQSubject, RelQBody)>
<!ATTLIST RelQuestion
RELQ_ID CDATA #REQUIRED
RELQ_CATEGORY CDATA #REQUIRED
RELQ_DATE CDATA #REQUIRED
RELQ_USERID CDATA #REQUIRED
RELQ_USERNAME CDATA #REQUIRED
>
<!ELEMENT RelQSubject (#PCDATA)>
<!ELEMENT RelQBody (#PCDATA)>
<!ELEMENT RelComment (RelCText)>
<!ATTLIST RelComment
RELC_ID CDATA #REQUIRED
RELC_DATE CDATA #REQUIRED
RELC_USERID CDATA #REQUIRED
RELC_USERNAME CDATA #REQUIRED
RELC_RELEVANCE2RELQ CDATA #REQUIRED
>
<!ELEMENT RelCText (#PCDATA)>
]>
<xml version="1.0">

	<Thread THREAD_SEQUENCE="Q2901">
		<RelQuestion RELQ_ID="Q2901" RELQ_CATEGORY="Salary and Allowances" RELQ_DATE="2012-06-30 13:29:22" RELQ_USERID="U9366" RELQ_USERNAME="rhnab">
			<RelQSubject>hi,can anyone give me an idea about grade 109 pay scale in hamad medical cooperation?</RelQSubject>
			<RelQBody>hi,can anyone give me an idea about grade 109 pay scale in hamad medical cooperation? If HR give me an offer can i give it for a review? will it affect the current offer?</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2901_C1" RELC_DATE="2012-07-01 20:44:31" RELC_USERID="U9366" RELC_USERNAME="rhnab" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>pay scale of 108 is 6500 so how can it be the same for 109?</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2902">
		<RelQuestion RELQ_ID="Q2902" RELQ_CATEGORY="Family Life in Qatar" RELQ_DATE="2009-12-14 09:52:36" RELQ_USERID="U5547" RELQ_USERNAME="qatari">
			<RelQSubject>quick and reasonable courier service?</RelQSubject>
			<RelQBody>Need to courier a parcel to Europe, what is the best company to use? 
considering cost and 3-4 days for delivery?

thanks
</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2902_C1" RELC_DATE="2009-12-14 10:20:10" RELC_USERID="U5407" RELC_USERNAME="algadomain" RELC_RELEVANCE2RELQ="Good">
			<RelCText>try ARAMEX</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2902_C2" RELC_DATE="2009-12-14 10:28:04" RELC_USERID="U4396" RELC_USERNAME="mohammed.ahmed" RELC_RELEVANCE2RELQ="Good">
			<RelCText>ARAMEX !
here is the phone no. in case u need it - 4506611. </RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2902_C3" RELC_DATE="2009-12-14 10:42:23" RELC_USERID="U6051" RELC_USERNAME="shajitomy" RELC_RELEVANCE2RELQ="Good">
			<RelCText>available cheap &amp; with reasonable price..,\\ARAMEX..Tel. No.as quoted by others...
Others are double costlier than..this</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2902_C4" RELC_DATE="2009-12-14 11:31:32" RELC_USERID="U1211" RELC_USERNAME="my_kris2ffer" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>pm me i will tell u exactly. its part of my jb... :D</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2902_C5" RELC_DATE="2009-12-14 13:05:11" RELC_USERID="U413" RELC_USERNAME="supermanqatar" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>All courier companies says they are good. In my experience all same.  </RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2902_C6" RELC_DATE="2009-12-14 13:23:06" RELC_USERID="U9367" RELC_USERNAME="mariad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>If it is for Europe, try Aramex. If it is for India try ST cargo and courier.</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2903">
		<RelQuestion RELQ_ID="Q2903" RELQ_CATEGORY="Visas and Permits" RELQ_DATE="2011-11-21 20:14:01" RELQ_USERID="U6225" RELQ_USERNAME="nishu441">
			<RelQSubject>Family RP from MOI</RelQSubject>
			<RelQBody>Anybody is there who received a family RP from Gharaffa immigration recently? As per the new rule family RP application need to be submit in MOI instead of MOL. But I would like to know the procedures in Immigration if there is any changes for the application form and requirement ect... please share your experience here and I&apos;m sure it will help others!

Thanks</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2903_C1" RELC_DATE="2011-11-22 07:43:35" RELC_USERID="U9368" RELC_USERNAME="sudheesh kumar" RELC_RELEVANCE2RELQ="Good">
			<RelCText>No change in the procedure only application form change . Submit the application on Ist floor of building no.2 .</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2903_C2" RELC_DATE="2011-11-22 07:49:06" RELC_USERID="U9369" RELC_USERNAME="Aneesh K J" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Thanks Sudheesh for your comment? did u sumbmit application to MOI? is there very strict for releasing family visa.can u share your experiences? plss</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2903_C3" RELC_DATE="2011-11-22 08:20:32" RELC_USERID="U6225" RELC_USERNAME="nishu441" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>could any one share there experience with MOI who already got the family RP? is there still strict to release the RP?</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2903_C4" RELC_DATE="2011-11-22 08:28:43" RELC_USERID="U6364" RELC_USERNAME="curlycues06" RELC_RELEVANCE2RELQ="Good">
			<RelCText>I just got a list of requirements for FAMILY RESIDENCE VISA from gharaffa immigration and these are:

1. Passport copies of wife and child/ren
2. Marriage Certificate (Ratified from Ministry of Foreign Affairs-Qatar)
3. Birth Certificate/s (Ratified from Ministry of Foreign Affairs-Qatar)
4. Passport and ID of Applicant (Husband)
5. Approval Letter with Job and Salary description from work (sponsor)- Attested from Ministry of Labor-Qatar
6. Bank Statement of salary for (6) months
7. Educational Certificate of applicant

Hope this would help.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2903_C5" RELC_DATE="2011-11-22 12:02:58" RELC_USERID="U9368" RELC_USERNAME="sudheesh kumar" RELC_RELEVANCE2RELQ="Good">
			<RelCText>I got the information from MOI that it is same like MOL . I sm still not submitted waiting for NOC from my employer. If you are working in a private firm it is better to get attest your contact copy from MOL.
Thank You.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2903_C6" RELC_DATE="2011-11-23 08:12:26" RELC_USERID="U9369" RELC_USERNAME="Aneesh K J" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>From where u heard regarding salary [QR.8,000/-]? Information from MOI there is no change in requirements for family visa..</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2904">
		<RelQuestion RELQ_ID="Q2904" RELQ_CATEGORY="Qatar Living Lounge" RELQ_DATE="2009-10-25 13:35:58" RELQ_USERID="U4410" RELQ_USERNAME="esther">
			<RelQSubject>voda simcard</RelQSubject>
			<RelQBody>each time im checking my balance with voda...there is a last message such as you have 30 minutes free call...but i dont know how i can use it...can someone tell me is it true or what...if true how i can use it..because each time im reloading it is adding and adding more minutes..from 30 minutes its now coming more than an hour free minutes...</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2904_C1" RELC_DATE="2009-10-25 13:45:05" RELC_USERID="U3903" RELC_USERNAME="shyams" RELC_RELEVANCE2RELQ="Good">
			<RelCText>come on... r u serious, didnt anyone tell you about the free vodafone minutes on every recharge. if not, then check on www.vodafone.com.qa, these are the vodafone free minutes, which you can use to call other vodafone nos for free. :-)</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2904_C2" RELC_DATE="2009-10-25 14:15:15" RELC_USERID="U7346" RELC_USERNAME="yousefmsh" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>I have the same Problim , all i know they do not have vodaphone phone and still adding minutes ,and i will loose it if not used .  </RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2904_C3" RELC_DATE="2009-10-25 14:30:29" RELC_USERID="U9370" RELC_USERNAME="ramgiri" RELC_RELEVANCE2RELQ="Good">
			<RelCText>At first voda phone is heda phone. if you try to call international, you should try more then 30 time. 
     frns,it is 100% true. if you have free calls and you don&apos;t know where &amp; how to use, give me i will use. because i know the......
  
 you should know by your self. cause ,it is very simple to know. 
</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2904_C4" RELC_DATE="2009-10-30 10:56:04" RELC_USERID="U3903" RELC_USERNAME="shyams" RELC_RELEVANCE2RELQ="Good">
			<RelCText>I am vodafone customer who was mad at your state earlier. then lately found out, if you try calling asian countries in the evening you wont get through, when i tried during noon its smooth. and for europe and US its always open. so then i started appreciating the vodafone offer for 50 DH international call, there must be some compromise atleast.... so lets live with it. and happy to hold one. </RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2905">
		<RelQuestion RELQ_ID="Q2905" RELQ_CATEGORY="Advice and Help" RELQ_DATE="2009-04-04 15:55:07" RELQ_USERID="U2110" RELQ_USERNAME="ollie">
			<RelQSubject>which bank gives the best car loan?</RelQSubject>
			<RelQBody>I am in a verge of making a decision whether I should get a car loan or just lease a car. 

If I decide to get a loan from the bank. Which bank gives the best customer service and lowest interest rate.

If you know a car I can buy. Thats superb!!!!</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2905_C1" RELC_DATE="2009-04-04 17:09:04" RELC_USERID="U4912" RELC_USERNAME="injinuity" RELC_RELEVANCE2RELQ="Good">
			<RelCText>all the banks pretty much charge the same rates... the differentiating factor is only the service element... from personal experiences..commercialbank seems to be the best... i highly reccomend them. 

J.J</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2905_C2" RELC_DATE="2009-04-04 17:21:21" RELC_USERID="U2110" RELC_USERNAME="ollie" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>wow! thanks!

I will give &apos;em a ring anytime tomorrow to check that out...

</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2905_C3" RELC_DATE="2009-04-04 17:24:53" RELC_USERID="U158" RELC_USERNAME="LAMBORJEEPNEY" RELC_RELEVANCE2RELQ="Good">
			<RelCText>your bank we&apos;re your salary is, it is easier that way. most banks now offer 4.5% ineterest on car loan. go to any car dealer you prefer, they will give you full details. Got mine from Doha Bank.

&quot;katas ng qatar&quot;</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2905_C4" RELC_DATE="2009-04-04 18:07:14" RELC_USERID="U2110" RELC_USERNAME="ollie" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>yeah! I would love to...

What car are we talking about here and the price coz I have noticed that Doha isnt a very big city and I will only use it to drive to work and grocery and night outs during the weekend. So I dont mind going for a not so expensive but good car...if second hand should be handled carefully and wont be having any car wrecks in the future

pls give me his number</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2906">
		<RelQuestion RELQ_ID="Q2906" RELQ_CATEGORY="Socialising" RELQ_DATE="2010-05-16 08:19:36" RELQ_USERID="U9371" RELQ_USERNAME="cheeseontoast">
			<RelQSubject>Cricket 20/20 where to watch?</RelQSubject>
			<RelQBody>Anyone know if any bars have been showing the 20/20 cricket so far? Need to find a venue for the final tonight (Sunday 16th)</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2906_C1" RELC_DATE="2010-05-16 09:01:28" RELC_USERID="U302" RELC_USERNAME="soniya" RELC_RELEVANCE2RELQ="Good">
			<RelCText>http://www.cricinfo.com/</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2907">
		<RelQuestion RELQ_ID="Q2907" RELQ_CATEGORY="Health and Fitness" RELQ_DATE="2008-10-25 21:21:29" RELQ_USERID="U9372" RELQ_USERNAME="Rinner">
			<RelQSubject>Does anyone know if Sinutab is available here?</RelQSubject>
			<RelQBody>Hi,

 i have been trawling the pharmacies here to try to find some Sinutab but to no avail..

Dies anyone know if it is available here anywhere ir is there a decent alternative? When i get Sinusitus its th eonly thing that works for me!

Thanks</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2907_C1" RELC_DATE="2008-10-25 21:44:26" RELC_USERID="U2123" RELC_USERNAME="hotandsticky" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Yeah its right next to the Nyquil. Seriously try claritine instead. Mat need a prescription here though.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2907_C2" RELC_DATE="2008-10-25 22:18:37" RELC_USERID="U3222" RELC_USERNAME="allymae" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Im using also sinutab but you cannot find sinutab here try to use the panadol for sinus. It really works based from im experience.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2907_C3" RELC_DATE="2008-10-25 22:26:06" RELC_USERID="U9373" RELC_USERNAME="michelle berry" RELC_RELEVANCE2RELQ="Good">
			<RelCText>You can try Panadol Sinus tablets.  They seem to be the closest to Sinutab here. If you are still battling, you can also try Vibrosil Nasal Spray.  Both have helped me.  Good luck. 
</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2908">
		<RelQuestion RELQ_ID="Q2908" RELQ_CATEGORY="Qatar Living Lounge" RELQ_DATE="2010-01-19 10:44:24" RELQ_USERID="U493" RELQ_USERNAME="Formatted Soul">
			<RelQSubject>Nissan Offer</RelQSubject>
			<RelQBody>Saw an ad in today&apos;s GT.. some offer for Nissan Vehicles. Pathfinder for QR. 89,000/- onwards...and xterra is QR.93,000. and Armada is QR.118,000. 

I thought Pathfinder is more expensive than Xttera. Anyone know why Pathfinder is so cheap? 
Did the prices come down or is it a good offer price?
</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2908_C1" RELC_DATE="2010-01-19 10:46:26" RELC_USERID="U210" RELC_USERNAME="DaRuDe" RELC_RELEVANCE2RELQ="Good">
			<RelCText>they want to get rid of old models.
&lt;img src=&quot;http://www.qatarliving.com/files/images/Da.gif&quot;&gt;

</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C2" RELC_DATE="2010-01-19 10:50:37" RELC_USERID="U689" RELC_USERNAME="Arien" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Basic ones FS , fully loaded ones will cost much more </RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C3" RELC_DATE="2010-01-19 10:52:26" RELC_USERID="U493" RELC_USERNAME="Formatted Soul" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Da I was thinking of Xttera or Fortuner...
Pathfinder looks tempting...cant wait to check it out..


&lt;a href=&quot;http://s434.photobucket.com/albums/qq67/formattedsoul/?action=view&amp;current=0003.gif&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;http://i434.photobucket.com/albums/qq67/formattedsoul/0003.gif&quot; border=&quot;0&quot; alt=&quot;Photobucket&quot;&gt;&lt;/a&gt;</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C4" RELC_DATE="2010-01-19 10:56:22" RELC_USERID="U493" RELC_USERNAME="Formatted Soul" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Arien for me Baisc is enough....all I need is a Auto gear, power windows and a CD player:) 

If you get time can you check it out?? as its close by your place?? 

&lt;a href=&quot;http://s434.photobucket.com/albums/qq67/formattedsoul/?action=view&amp;current=0003.gif&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;http://i434.photobucket.com/albums/qq67/formattedsoul/0003.gif&quot; border=&quot;0&quot; alt=&quot;Photobucket&quot;&gt;&lt;/a&gt;</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C5" RELC_DATE="2010-01-19 10:59:21" RELC_USERID="U493" RELC_USERNAME="Formatted Soul" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>

Da.. Fortuner full option is 94K...

I dont like the look of Patrol:) 


&lt;a href=&quot;http://s434.photobucket.com/albums/qq67/formattedsoul/?action=view&amp;current=0003.gif&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;http://i434.photobucket.com/albums/qq67/formattedsoul/0003.gif&quot; border=&quot;0&quot; alt=&quot;Photobucket&quot;&gt;&lt;/a&gt;</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C6" RELC_DATE="2010-01-19 11:00:32" RELC_USERID="U491" RELC_USERNAME="KHATTAK" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText> &lt;code&gt;&lt;b&gt;Fortuner is hopeless :(

Pathfinder is excellent...but doesnt give a look of a family car...better go for a compact SUV.&lt;/code&gt;&lt;/b&gt;       

----------------------------------------------------------------&lt;i&gt;Give me some SunShine......Give me some Rain
Give me another Chance...I wanna grow up once Again&lt;/i&gt;
</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C7" RELC_DATE="2010-01-19 11:02:41" RELC_USERID="U497" RELC_USERNAME="blablubliblrrr" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Who cares about the look?Engine matters.Patrol is virile,not like exterra or fortuner.. I must say,a shabaab vehicle. </RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C8" RELC_DATE="2010-01-19 11:04:32" RELC_USERID="U689" RELC_USERNAME="Arien" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Fs .. I will.Path finder rght? </RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C9" RELC_DATE="2010-01-19 11:13:08" RELC_USERID="U689" RELC_USERNAME="Arien" RELC_RELEVANCE2RELQ="Good">
			<RelCText>2009 models are on offer.

Basic XE QR 101 000

automatic transmission, power window 
NO CD player


XE QR 111 000

CD player m cruise control, Alloy wheel, Power window..etc</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C10" RELC_DATE="2010-01-19 11:15:16" RELC_USERID="U497" RELC_USERNAME="blablubliblrrr" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Females have no taste when it comes to selection of vehicles..Sad!</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C11" RELC_DATE="2010-01-19 11:17:33" RELC_USERID="U302" RELC_USERNAME="soniya" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>blablu, can u just keep shut ur big mouth !!! its like as if u men never ask for ne new model queries..SAD, that u think like this..</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C12" RELC_DATE="2010-01-19 11:21:30" RELC_USERID="U497" RELC_USERNAME="blablubliblrrr" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>:$ I poo&apos;d on my pants.. </RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C13" RELC_DATE="2010-01-19 11:23:41" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Xttera...has a sporty look...2009 onwards it has a lot of features...
Patrol is fuel efficient of the 3 &amp; 
Pathfinder has the best off road ability of the 3.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C14" RELC_DATE="2010-01-19 11:29:31" RELC_USERID="U497" RELC_USERNAME="blablubliblrrr" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Shame on me?Why? </RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C15" RELC_DATE="2010-01-19 11:32:44" RELC_USERID="U302" RELC_USERNAME="soniya" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>think urself bla...</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C16" RELC_DATE="2010-01-19 11:33:16" RELC_USERID="U689" RELC_USERNAME="Arien" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Blablu - Its not just this thread and your comments, i know you are stalkin, and i dont need to explain it here.you know it and gro up.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C17" RELC_DATE="2010-01-19 11:33:48" RELC_USERID="U497" RELC_USERNAME="blablubliblrrr" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>I got a dimwit soniya!</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C18" RELC_DATE="2010-01-19 11:35:18" RELC_USERID="U497" RELC_USERNAME="blablubliblrrr" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Stalking who?You?</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C19" RELC_DATE="2010-01-19 11:37:58" RELC_USERID="U495" RELC_USERNAME="Omar Waheed." RELC_RELEVANCE2RELQ="Bad">
			<RelCText>and bablu you are still under age to drive a car.. am i right

_______________________

&apos;&apos; Live for Nothing or Die for Something &apos;&apos;
_______________________</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C20" RELC_DATE="2010-01-19 11:38:15" RELC_USERID="U497" RELC_USERNAME="blablubliblrrr" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>By the word &apos;engine&apos; I meant power of the vehicle.We guys used to look the power,No idea about you.I really dint get the concept of going back to 80&apos;s and 90&apos;s?</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C21" RELC_DATE="2010-01-19 11:38:45" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>FS you got a stalker???? Cool ;)





**** Aal Izz Well****</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C22" RELC_DATE="2010-01-19 11:44:45" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Power comes from red bull</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C23" RELC_DATE="2010-01-19 11:47:19" RELC_USERID="U689" RELC_USERNAME="Arien" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Jack .. Musli Power lol</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C24" RELC_DATE="2010-01-19 11:50:32" RELC_USERID="U497" RELC_USERNAME="blablubliblrrr" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Your grammar is atrocious Omar.I cannot follow you.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C25" RELC_DATE="2010-01-19 12:00:52" RELC_USERID="U497" RELC_USERNAME="blablubliblrrr" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Take a guess!</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C26" RELC_DATE="2010-01-19 12:06:13" RELC_USERID="U3351" RELC_USERNAME="the bee" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Omer Your English teacher should be fired.Go back to school man,but a little better one this time please.
 
</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C27" RELC_DATE="2010-01-19 12:14:18" RELC_USERID="U495" RELC_USERNAME="Omar Waheed." RELC_RELEVANCE2RELQ="Bad">
			<RelCText>you will get to know beta very soon.. just wait and watch OK 

Peace OUT

_______________________

&apos;&apos; Live for Nothing or Die for Something &apos;&apos;
_______________________</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C28" RELC_DATE="2010-01-19 12:19:39" RELC_USERID="U497" RELC_USERNAME="blablubliblrrr" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>A puppeteer and a puppet!!lol</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C29" RELC_DATE="2010-01-19 12:22:35" RELC_USERID="U60" RELC_USERNAME="Rizks" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>are we discussing about Nissan or BulBul ?

i mean blablubiliblrrrr....watever tat id is ?? 
&lt;a title=&quot;Everything you need to know about living in Doha, Qatar&quot; href=&quot;http://www.qatarliving.com&quot;&gt;&lt;img src=&quot;http://static.qatarliving.com/badges/150x50_iloveqatarliving.gif&quot; alt=&quot;Everything you need to know about living in Doha, Qatar&quot; /&gt;&lt;/a&gt;</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C30" RELC_DATE="2010-01-19 12:24:48" RELC_USERID="U2861" RELC_USERNAME="chevydjak" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>i like path as well as I like chevy trail too...which one is better?

&lt;b&gt;&quot;BRING IT ON SUPERCHAKA!!!&quot;&lt;/b&gt;</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C31" RELC_DATE="2010-01-19 13:16:27" RELC_USERID="U493" RELC_USERNAME="Formatted Soul" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>I ignored long time back...still he wont iognore me..lol Anywayz as if I care?? lol

WK Who does he sound like? lol 


&lt;a href=&quot;http://s434.photobucket.com/albums/qq67/formattedsoul/?action=view&amp;current=0003.gif&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;http://i434.photobucket.com/albums/qq67/formattedsoul/0003.gif&quot; border=&quot;0&quot; alt=&quot;Photobucket&quot;&gt;&lt;/a&gt;</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C32" RELC_DATE="2010-01-19 13:29:56" RELC_USERID="U689" RELC_USERNAME="Arien" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>FS prices I have put above. am sure the 2010 model will be ready for launch , thts why they are clearing the 2009 off.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C33" RELC_DATE="2010-01-19 13:33:51" RELC_USERID="U497" RELC_USERNAME="blablubliblrrr" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Yes Formatted Soul,you were ignoring me the day you start having an opinion.Sad!</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C34" RELC_DATE="2010-01-19 13:36:59" RELC_USERID="U998" RELC_USERNAME="snessy" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Wow, so much drama over a car, LOL!

*****If you haven&apos;t got anything nice to say, don&apos;t say anything at all*****</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C35" RELC_DATE="2010-01-19 13:37:15" RELC_USERID="U60" RELC_USERNAME="Rizks" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>Nissan Pathfinder 2005 Model for Sale !!
Full Automatic with AirBag, School bags and Trash bags...lol
It also has a &quot;QataLiving.com&quot; sticker stuck on the trunk.

Price: Qrs.89,000/- but especial rate to FS, u can take it for Qrs.80,000/-.

If Interested, my PM is open 24/7 anytime.

thank you
&lt;a title=&quot;Everything you need to know about living in Doha, Qatar&quot; href=&quot;http://www.qatarliving.com&quot;&gt;&lt;img src=&quot;http://static.qatarliving.com/badges/150x50_iloveqatarliving.gif&quot; alt=&quot;Everything you need to know about living in Doha, Qatar&quot; /&gt;&lt;/a&gt;</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C36" RELC_DATE="2010-01-19 13:38:25" RELC_USERID="U210" RELC_USERNAME="DaRuDe" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>call them again and check how much is Safari or Infiniti FX35

&lt;img src=&quot;http://www.qatarliving.com/files/images/Da.gif&quot;&gt;

</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C37" RELC_DATE="2010-01-19 13:42:27" RELC_USERID="U493" RELC_USERNAME="Formatted Soul" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Rizkssss...thx but no thx...:) I dont wanna loose my hair too... heard that the old user became bald and beautiful after using that car!! lol 

DA I think they are closed now....




&lt;a href=&quot;http://s434.photobucket.com/albums/qq67/formattedsoul/?action=view&amp;current=0003.gif&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;http://i434.photobucket.com/albums/qq67/formattedsoul/0003.gif&quot; border=&quot;0&quot; alt=&quot;Photobucket&quot;&gt;&lt;/a&gt;</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2908_C38" RELC_DATE="2010-01-20 08:23:55" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Is size that important?...I mean Engine size....obviously!</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2909">
		<RelQuestion RELQ_ID="Q2909" RELQ_CATEGORY="Doha Shopping" RELQ_DATE="2012-09-24 15:38:33" RELQ_USERID="U6804" RELQ_USERNAME="HeniHuDz">
			<RelQSubject>Online promotional ads</RelQSubject>
			<RelQBody>Salaam/hello

Can anyone point me to some online ads so I can get a guess at the prices in Qatar (food, clothing, furnishings, laptop, TV, kitchen items, etc) I&apos;ve checked out Carrefour but I didn&apos;t see much; thanks!</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2909_C1" RELC_DATE="2012-09-24 16:01:21" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Good">
			<RelCText>check qgrabs :)</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2909_C2" RELC_DATE="2012-09-24 16:28:33" RELC_USERID="U6804" RELC_USERNAME="HeniHuDz" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Thanks alot! cheers!</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2909_C3" RELC_DATE="2012-09-24 17:09:51" RELC_USERID="U28" RELC_USERNAME="osamabawab" RELC_RELEVANCE2RELQ="Good">
			<RelCText>u can check this for online shopping:
http://doha.dbanksouq.com/
generally they are overpriced, but it may help u to get an idea</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2909_C4" RELC_DATE="2012-09-24 21:45:48" RELC_USERID="U9374" RELC_USERNAME="Arun Chandwani" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>The most determinative sentence
which should alwayz be followed in life-
THE RACE IS NOT OVER BCOZ I HAVE NOT WON YET.!

Arun Yoga teacher
</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2909_C5" RELC_DATE="2012-09-24 21:52:35" RELC_USERID="U9374" RELC_USERNAME="Arun Chandwani" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Give thousand chances to your enemy
To become your friend.
But never give a single chance to your Friend
To become your enemy.

Practice &quot;Maitri&quot; Friendliness

Arun yoga teacher</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2910">
		<RelQuestion RELQ_ID="Q2910" RELQ_CATEGORY="Education" RELQ_DATE="2010-06-25 05:57:29" RELQ_USERID="U9375" RELQ_USERNAME="daciana">
			<RelQSubject>guitar lessons</RelQSubject>
			<RelQBody>I&apos;m interested in having guitar lessons. There is any one who can give me a clue?...thank you.Gabriela.</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2910_C1" RELC_DATE="2010-06-25 08:55:56" RELC_USERID="U8403" RELC_USERNAME="Khan_1980" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Near Lulu hyper there is music Center which gives classes for music, you can try there.
Thanks</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2910_C2" RELC_DATE="2010-06-25 09:28:19" RELC_USERID="U5946" RELC_USERNAME="M.E" RELC_RELEVANCE2RELQ="Good">
			<RelCText>There is a store near Jarir Bookstore that sells guitars and music instruments, there is a tutor there, he teaches guitar and piano, he&apos;s from the Philipines. I don&apos;t quite remember his name. But when you get there just ask anyone there about someone that teaches guitar and they will help you.
</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2910_C3" RELC_DATE="2010-06-25 13:09:45" RELC_USERID="U1667" RELC_USERNAME="xpatadventure" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Hello M.E.

Do you mean the Jarir bookstore on Salwa Road or the one on Al Rayan?

Can you give a rough direction where it is located?

Thanks a lot</RelCText>
		</RelComment>