<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xml [
<!ELEMENT xml (Thread*)>
<!ATTLIST xml 
version CDATA #REQUIRED
>
<!ELEMENT Thread (RelQuestion, RelComment*)>
<!ATTLIST Thread
 THREAD_SEQUENCE CDATA #REQUIRED
>
<!ELEMENT RelQuestion (RelQSubject, RelQBody)>
<!ATTLIST RelQuestion
RELQ_ID CDATA #REQUIRED
RELQ_CATEGORY CDATA #REQUIRED
RELQ_DATE CDATA #REQUIRED
RELQ_USERID CDATA #REQUIRED
RELQ_USERNAME CDATA #REQUIRED
>
<!ELEMENT RelQSubject (#PCDATA)>
<!ELEMENT RelQBody (#PCDATA)>
<!ELEMENT RelComment (RelCText)>
<!ATTLIST RelComment
RELC_ID CDATA #REQUIRED
RELC_DATE CDATA #REQUIRED
RELC_USERID CDATA #REQUIRED
RELC_USERNAME CDATA #REQUIRED
RELC_RELEVANCE2RELQ CDATA #REQUIRED
>
<!ELEMENT RelCText (#PCDATA)>
]>
<xml version="1.0">

	<Thread THREAD_SEQUENCE="Q2481">
		<RelQuestion RELQ_ID="Q2481" RELQ_CATEGORY="Life in Qatar" RELQ_DATE="2010-11-24 14:41:45" RELQ_USERID="U8902" RELQ_USERNAME="eeyouth20">
			<RelQSubject>from DUBAI to QATAR</RelQSubject>
			<RelQBody>i am currently working here in dubai and i got an offer from qatar company.. they offered 8000QAR +camp accommodation +meal and transportation is provided by the company... will this be enough to accept the offer? how good is the transportation there in qatar?</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2481_C1" RELC_DATE="2010-11-24 14:51:44" RELC_USERID="U7263" RELC_USERNAME="mohseen26" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>If you are single then its ok you can enjoy.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2481_C2" RELC_DATE="2010-11-24 14:53:39" RELC_USERID="U604" RELC_USERNAME="nishantvshah" RELC_RELEVANCE2RELQ="Good">
			<RelCText>depends on where the accommodation is.. how many people will live with you; what kind of food. Why dont u ask your company to provide you transportation and ask for 4k more as accommodation and food allowance. Most importantly; 8k isnt a great salary but it all again depends on your job profile and work experience.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2481_C3" RELC_DATE="2010-11-24 15:01:03" RELC_USERID="U2316" RELC_USERNAME="Hawk10" RELC_RELEVANCE2RELQ="Good">
			<RelCText>If the company is from Oil and Gas Industry or working for that Industry; then their accommodation and transport will be better. If it is normal construction company; they dont have good facilities. As far as your question of salary is concerned; you dont need to ask; as Dubai is not so different from Qatar and the currency is also the same.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2481_C4" RELC_DATE="2010-11-24 15:02:29" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Transport in the city is a nightmare.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2481_C5" RELC_DATE="2010-11-24 15:03:27" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>And life her is so relaxed that bachelors are excluded from many venues on 'Family Days.'</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2481_C6" RELC_DATE="2010-11-24 15:07:17" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>It basically means 'sharing'. The bathroom; the kitchen; the bedroom. So; privacy adieu.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2481_C7" RELC_DATE="2010-11-24 15:10:16" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>If you're here to work; eat; and sleep. No problem.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2481_C8" RELC_DATE="2010-11-24 15:10:30" RELC_USERID="U977" RELC_USERNAME="prettyice2007" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>like you share your room to 4 persons.. you got no privacy at all...</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2481_C9" RELC_DATE="2010-11-24 15:14:19" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>Camp is temporary. So; possibly porta cabin.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2481_C10" RELC_DATE="2010-11-24 15:14:53" RELC_USERID="U2316" RELC_USERNAME="Hawk10" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>I have Filipino friend; getting 5000 QR and he has his family also with him and 3 yrs old kid. Don't worry; you can manage.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2481_C11" RELC_DATE="2010-11-24 15:16:02" RELC_USERID="U8902" RELC_USERNAME="eeyouth20" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>ok... thank you again...</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2481_C12" RELC_DATE="2010-11-24 15:27:00" RELC_USERID="U401" RELC_USERNAME="arecel" RELC_RELEVANCE2RELQ="Good">
			<RelCText>8k ++ is okay eeyouth. just ask about the camp accom. if it's porta cabin and you are used to this then good. if not; then ask them about housing allow. but if your work place is in messaeeid or ras laffan; better take the camp accom. these places are far from doha.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2481_C13" RELC_DATE="2010-11-24 15:31:53" RELC_USERID="U1281" RELC_USERNAME="stanley_mnl" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>hehehe grab it and meet me in ramada heeheheh</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2481_C14" RELC_DATE="2010-11-24 16:36:50" RELC_USERID="U51" RELC_USERNAME="baldrick2dogs" RELC_RELEVANCE2RELQ="Good">
			<RelCText>The camp at NDIA is not too bad. Cabins are only a few years old and there are plenty facilities. Transport will be the yellow bus between camp and site - about 15 minutes driving max. Taxis tend not to call there so getting out on your own can be a hassle unless you get pally with a kabayan with a pickup truck at his disposal! If the salary is same as you get in Dubai you should be able to save more here.</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2482">
		<RelQuestion RELQ_ID="Q2482" RELQ_CATEGORY="Socialising" RELQ_DATE="2010-01-17 15:26:30" RELQ_USERID="U1295" RELQ_USERNAME="Jester">
			<RelQSubject>Tennis competitions</RelQSubject>
			<RelQBody>Hi; Would anyone know of any organised tennis competitions in Doha? Many Thanks Jessica</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2482_C1" RELC_DATE="2010-01-17 15:50:27" RELC_USERID="U2406" RELC_USERNAME="crecth" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>try badminton.. you will see the difference..</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2482_C2" RELC_DATE="2010-01-17 17:36:24" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>hi heart..how r u doing today?</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2483">
		<RelQuestion RELQ_ID="Q2483" RELQ_CATEGORY="Life in Qatar" RELQ_DATE="2009-11-05 08:25:05" RELQ_USERID="U8903" RELQ_USERNAME="thechi">
			<RelQSubject>Please help me to find out the nurseries which is till 3pm</RelQSubject>
			<RelQBody>Please advice me any good nurseries which is till 3. Contact numbers if possible... Thanks in advance!</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2483_C1" RELC_DATE="2009-11-05 09:18:06" RELC_USERID="U8903" RELC_USERNAME="thechi" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>nobody out ther? pls help</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2483_C2" RELC_DATE="2009-11-05 09:36:32" RELC_USERID="U8904" RELC_USERNAME="pauly" RELC_RELEVANCE2RELQ="Good">
			<RelCText>CROWN; behind gulf times DIMS also</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2483_C3" RELC_DATE="2009-11-05 09:46:16" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Al kulood Nursery school(Donbosco)at Bin Omran Nerar the Yarimuk Al Meera they are open until 5PM</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2483_C4" RELC_DATE="2009-11-05 09:55:44" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Mr. Pauly. Do you have the phone number for CROWN; behind gulf times.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2483_C5" RELC_DATE="2009-11-05 10:01:49" RELC_USERID="U3198" RELC_USERNAME="um Omar" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Melberry Bush- English system: 4502545 but it is until 02:30 pm from 06:30 am.. you can keep your child there longer time for an additional QR. 20/- for each extra hour.. Fees: QR. 1;400/- per month.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2483_C6" RELC_DATE="2009-11-05 10:57:14" RELC_USERID="U5212" RELC_USERNAME="mohammed riyaz" RELC_RELEVANCE2RELQ="Good">
			<RelCText>go to smart baby care ; back of Al-Meera ; they are very good. i am sending my daugter also.</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2484">
		<RelQuestion RELQ_ID="Q2484" RELQ_CATEGORY="Working in Qatar" RELQ_DATE="2012-09-01 11:08:12" RELQ_USERID="U8905" RELQ_USERNAME="bench_business">
			<RelQSubject>looking for rent a car BUDGET 1500</RelQSubject>
			<RelQBody>Im looking for a car for 1 month used for me to used daily for my work and business. i hope i can find and u can suggest wer can i find good car here in qatar</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2484_C1" RELC_DATE="2012-09-01 11:41:56" RELC_USERID="U2771" RELC_USERNAME="YAZLEB" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>no chance........try mopeds for that price ;-)</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2484_C2" RELC_DATE="2012-09-01 11:50:04" RELC_USERID="U8906" RELC_USERNAME="Vasim_Sayed" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>so what should be the minimum budget for rent a car for a month! and where should we find this; I dont have PR of Qatar too! is that a problem in getting a rent a car? thanks in advance! This is a real helpful site for visitors!</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2484_C3" RELC_DATE="2012-09-01 11:56:09" RELC_USERID="U2771" RELC_USERNAME="YAZLEB" RELC_RELEVANCE2RELQ="Good">
			<RelCText>around 2100qr for a small car like Seat Ibiza etc; they will tell u 2300-2400 flash the cash in front of them &#38; say 2000....hope for the best; yes u can drive on ur european license for 1 month....i think; until u get ur RP &#38; Qatari DL.....sorry i dont have the names or numbers for any; my husband dealt with them. google it or use qatcom online. goodluck</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2484_C4" RELC_DATE="2012-09-01 13:55:47" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Good">
			<RelCText>One week; not one month (I believe). Try Al Mufta for a good rental price. You won't get 1;500 per month though!</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2484_C5" RELC_DATE="2012-09-01 14:24:21" RELC_USERID="U8907" RELC_USERNAME="ahmadb900" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>we have sunny for rent 2013</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2484_C6" RELC_DATE="2012-09-08 00:49:37" RELC_USERID="U8908" RELC_USERNAME="razanm25" RELC_RELEVANCE2RELQ="Good">
			<RelCText>One of my friends have hired a Honda City 2008 for 1600 a month. You may get it for your budget.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2484_C7" RELC_DATE="2012-09-08 01:02:25" RELC_USERID="U8909" RELC_USERNAME="InTheChoiceTrap" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>where he/she was able to rent for that price it would be very helpful</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2485">
		<RelQuestion RELQ_ID="Q2485" RELQ_CATEGORY="Salary and Allowances" RELQ_DATE="2011-01-23 16:57:42" RELQ_USERID="U8910" RELQ_USERNAME="manikthr">
			<RelQSubject>QP Offer</RelQSubject>
			<RelQBody>I had an interview with department head and lead people ( not HR )at QP for the Grade-13 post.. and they said they will inform me the next procedure like medical chekups etc.. Does anybody have the idea how much it will take to complete the procedure and when can i get the offer letter. and please do let me know what will be the approximate salary and other allowances. If anybody have any idea; please share with me. Please.....</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2485_C1" RELC_DATE="2011-01-23 17:19:12" RELC_USERID="U6198" RELC_USERNAME="qcool" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>did u apply via their web site?</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2485_C2" RELC_DATE="2011-01-23 18:07:16" RELC_USERID="U8911" RELC_USERNAME="atractivo" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>what is the job category?</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2485_C3" RELC_DATE="2011-01-23 18:26:20" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Good">
			<RelCText>it will take 1 month</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2485_C4" RELC_DATE="2011-01-23 19:10:14" RELC_USERID="U7410" RELC_USERNAME="azm83" RELC_RELEVANCE2RELQ="Good">
			<RelCText>So basically you have accepted a job offer without even knowing what salary you are getting or what allowances are included?! Good one :) I suggest you call them and ask... there is nothing wrong with knowing what you are being offered!</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2486">
		<RelQuestion RELQ_ID="Q2486" RELQ_CATEGORY="Advice and Help" RELQ_DATE="2008-08-06 18:24:21" RELQ_USERID="U8912" RELQ_USERNAME="Problemado">
			<RelQSubject>what u think of phin</RelQSubject>
			<RelQBody>does ah phone number now can eat like ah chocolate?im only looking 4 help and advice!i have no business 4 grls..anyway tnx 4 ur reply....</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2486_C1" RELC_DATE="2008-08-06 19:28:06" RELC_USERID="U366" RELC_USERNAME="Dracula" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>oryx is my goattye's cousin! :P &#60;a href="http://tinypic.com" target="_blank"&#62;&#60;img src="http://i35.tinypic.com/111l5wz.jpg" border="0" alt="Image and video hosting by TinyPic"&#62;&#60;/a&#62;</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2487">
		<RelQuestion RELQ_ID="Q2487" RELQ_CATEGORY="Family Life in Qatar" RELQ_DATE="2008-11-27 10:17:24" RELQ_USERID="U1254" RELQ_USERNAME="Bahrainee">
			<RelQSubject>which is the best hospital for baby vaccinations?</RelQSubject>
			<RelQBody>Our baby is scheduled for his six month vaccination and we we wondering where to take him. some people say it depends on the freshness of the vaccine. are all common vaccinations available everywhere. Price is not an issue as long as our boy is safe; preferably afternoon clinics.</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2487_C1" RELC_DATE="2008-11-27 11:15:43" RELC_USERID="U642" RELC_USERNAME="draj" RELC_RELEVANCE2RELQ="Good">
			<RelCText>just take baby to Al-ahili hospital... i do the same for my baby...</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2487_C2" RELC_DATE="2008-11-27 11:35:23" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Hamad Medical Health Center... Go for it.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2487_C3" RELC_DATE="2008-11-27 11:35:49" RELC_USERID="U302" RELC_USERNAME="soniya" RELC_RELEVANCE2RELQ="Good">
			<RelCText>My baby just completed 6months and i m over with her vaccination..Her next due will be after 1yr..I delivered her in DOHA CLINIC..so i prefer that..Its ok..U can visit HMC also coz i have heard most of the vaccinations r getting supplied from there itself..</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2488">
		<RelQuestion RELQ_ID="Q2488" RELQ_CATEGORY="Education" RELQ_DATE="2010-01-09 00:19:46" RELQ_USERID="U878" RELQ_USERNAME="Tanuzahir">
			<RelQSubject>Arabic Teacher</RelQSubject>
			<RelQBody>hello i am moving from the US to Doha end of Jan. I am looking for a female arabic teacher that can come and teach me Arabic at home. I want to learn to speak arabic; but also would like to learn how to read the Quran; as i am a muslima and never learned. Can someone give me info on how to find an arabic teacher; that will come home and teach.</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2488_C1" RELC_DATE="2010-01-09 00:31:46" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Good">
			<RelCText>we u come to Qatar u can call minestery of awqaf they well teach u free of charg welcome to qatar and best wishes</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2488_C2" RELC_DATE="2010-01-09 00:32:44" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>we = wen</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2488_C3" RELC_DATE="2010-01-09 00:33:27" RELC_USERID="U1795" RELC_USERNAME="salah2008" RELC_RELEVANCE2RELQ="Good">
			<RelCText>u don't have to hire an Arabic teacher; u can visit the Qatar Islamic Cultural Centre(Fanar) http://www.islamicfinder.org/ they will teach u everything about Islam; free of charge</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2488_C4" RELC_DATE="2010-01-09 08:56:22" RELC_USERID="U8913" RELC_USERNAME="anitabong" RELC_RELEVANCE2RELQ="Good">
			<RelCText>salamualaykum sister; I know there is one Syrian lady in my compound that i havent met. she gives a private lesson but i dont know whether she can go to your place. finding a private arabic need an extra effort. however u can try to look for ladies classes available; they teach tajweed and quranic arabic. I myself is still looking for it as i cannot find morning class (full) while some classes are in the evening. please send me private message whenever you need help.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2488_C5" RELC_DATE="2010-02-22 09:41:46" RELC_USERID="U8914" RELC_USERNAME="hany13" RELC_RELEVANCE2RELQ="Good">
			<RelCText>iam a lady arabic teacher for non-arabic speakers have good experience 6598336 this my husband page</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2488_C6" RELC_DATE="2013-03-06 10:03:10" RELC_USERID="U7956" RELC_USERNAME="designphoto" RELC_RELEVANCE2RELQ="Good">
			<RelCText>So many people asked me to teach them Arabic Language ; how to read Quran and Tajweed But do you know the life goes fast ; there is no time to go there home so I decided to make a websitewhich is help inshallah my friend to teach themself this way worked with me i teach myself PHOTOSHOP from internet Qaida Noorania : It help to spell Quranic words by watching and listening Qataria : http://arabicmajles.ucoz.com/index/arabic/0-2 Sudia : http://arabicmajles.ucoz.com/index/learn_about_islam/0-6 Quran Audio Translation http://arabicmajles.ucoz.com/index/quran_audio_translation/0-8 Altajweed http://arabicmajles.ucoz.com/index/0-7 Islamic PDF books http://arabicmajles.ucoz.com/index/islamic_books/0-26 How to write Arabic Letters http://arabicmajles.ucoz.com/index/arabic_course/0-5 Arabic Tutor Books http://arabicmajles.ucoz.com/index/arabic_teaching_book/0-30 I have another website for ArabLearner http://alyousfi.at.ua/</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2488_C7" RELC_DATE="2013-05-20 04:29:07" RELC_USERID="U8915" RELC_USERNAME="aanaa055" RELC_RELEVANCE2RELQ="Good">
			<RelCText>ADEL MOHAMMED ARABIC TEACHER EGYPTION TO CONTACT ME 55265719 - 77940211</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2489">
		<RelQuestion RELQ_ID="Q2489" RELQ_CATEGORY="Life in Qatar" RELQ_DATE="2008-11-30 19:50:59" RELQ_USERID="U5639" RELQ_USERNAME="yazz771">
			<RelQSubject>Weather in Qatar in december</RelQSubject>
			<RelQBody>Hi all; I'm coming in 2 weeks to Doha and I was wondering how's the weather in december. Should I bring winter clothes? Jacket? Coat? Wool etc... I can see in the forcasts that it can go down to 10deg sometimes but this doesn't mean much since there's a lot of factors for example 10deg Celsius is ok in Boston but if you go to washington you're gonna freeze in 10deg C TY</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2489_C1" RELC_DATE="2008-11-30 20:20:17" RELC_USERID="U188" RELC_USERNAME="novita77" RELC_RELEVANCE2RELQ="Good">
			<RelCText>dont have to bring a coat; light jumper / cardigan would be fine.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2489_C2" RELC_DATE="2008-11-30 20:20:48" RELC_USERID="U8916" RELC_USERNAME="dewelle" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>I dont know the exact degrees but to be sure as they say it is indeed very cold at that time.Bring winter clothes as an advice..;;;;</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2489_C3" RELC_DATE="2008-11-30 20:36:25" RELC_USERID="U114" RELC_USERNAME="GodFather." RELC_RELEVANCE2RELQ="Good">
			<RelCText>Temperature at night does drop around 10C. Yes it does feel cold here when it is 10C especially if you go out. There is no heating in the house here so you gonna feel cold.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2489_C4" RELC_DATE="2008-11-30 20:47:30" RELC_USERID="U7610" RELC_USERNAME="Giridharan.T.R." RELC_RELEVANCE2RELQ="Good">
			<RelCText>Average night temp during December will be around 13 to 15 degC. Warm track suits; woolen pullovers/fleece would be fine. It will be very cold(below 10 degC) from Mid Jan up to Feb end.</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2490">
		<RelQuestion RELQ_ID="Q2490" RELQ_CATEGORY="Advice and Help" RELQ_DATE="2009-10-03 20:20:54" RELQ_USERID="U1000" RELQ_USERNAME="Salman sajid">
			<RelQSubject>can some 1 give me cats or kittens</RelQSubject>
			<RelQBody>hi and hello i need cats or kittens if you have because my cat deid yeterday :[ but you can help me if you have cats i will buy but the priceshould be between 100-150 you can help me :] if you can call me my number******6983357****** hotmail******salmankhan_tweety@hotmail.com******</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2490_C1" RELC_DATE="2009-10-04 05:59:12" RELC_USERID="U51" RELC_USERNAME="baldrick2dogs" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>QAWS! &#60;a href="http://www.flickr.com/photos/b_2_d/3615935822/" title="The Pearl Development Panorama by baldrick2dogs; on Flickr"&#62;&#60;img src="http://farm4.static.flickr.com/3351/3615935822_2ca87f726f_m.jpg" width="240" height="57" alt="The Pearl Development Panor</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2491">
		<RelQuestion RELQ_ID="Q2491" RELQ_CATEGORY="Education" RELQ_DATE="2010-06-25 11:14:57" RELQ_USERID="U5135" RELQ_USERNAME="BASSAM KHALIL">
			<RelQSubject>plz help ! its urgent....</RelQSubject>
			<RelQBody>hi friends! can u plz help me; i want to study engineering and i cant decide between CNA-Q and QU(qatar university) ;;; so plz advise which one is better .. thanks in advance.... =)</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2491_C1" RELC_DATE="2010-06-25 11:19:58" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Good">
			<RelCText>hello qatar uni is much better than north atlantic wish you all the best</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2491_C2" RELC_DATE="2010-06-25 12:40:31" RELC_USERID="U5135" RELC_USERNAME="BASSAM KHALIL" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>thanks both of u for ur help ;;and i was interested in doing chemical engineering ;;;and i cant go to texas (its very expensive :-( ;;;thats why ;;so plz tell me ........which one from the above options ;;;plz</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2491_C3" RELC_DATE="2010-06-25 13:34:24" RELC_USERID="U373" RELC_USERNAME="Mandilulur" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>CNA-Q doesn't offer a bachelor's degree.</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2491_C4" RELC_DATE="2010-06-25 18:29:01" RELC_USERID="U8917" RELC_USERNAME="arabic.dream.knight" RELC_RELEVANCE2RELQ="Good">
			<RelCText>According to the above information; it looks you have a chance at Q U. I undrstood you have a budget constraints; so why don't u try other Arabic universities; like the Jordan Uminersity (http://www.ju.edu.jo/home.aspx) its not expensive and arabic respectful university and accrediated internationally; and the study in English. All the Luck.</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2492">
		<RelQuestion RELQ_ID="Q2492" RELQ_CATEGORY="Doha Shopping" RELQ_DATE="2011-11-20 17:03:33" RELQ_USERID="U5547" RELQ_USERNAME="qatari">
			<RelQSubject>Birthday gift ideas</RelQSubject>
			<RelQBody>Hi All ! Appreciate your suggestions for A Birthday Gift for 7 years old girl (daughter of my friend ).. Thanks in advance.</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2492_C1" RELC_DATE="2011-11-20 17:16:05" RELC_USERID="U2575" RELC_USERNAME="surabiabi" RELC_RELEVANCE2RELQ="Good">
			<RelCText>give her lots of chocolates &#38; ice-creams..........</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2492_C2" RELC_DATE="2011-11-20 17:59:36" RELC_USERID="U56" RELC_USERNAME="flor1212" RELC_RELEVANCE2RELQ="Good">
			<RelCText>or a nice sweater or light jacket. Even a lunch box will do!</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2492_C3" RELC_DATE="2011-11-20 18:38:46" RELC_USERID="U1058" RELC_USERNAME="rubypavino" RELC_RELEVANCE2RELQ="Good">
			<RelCText>for a 7yrs.old girl;there are so many to buy like Barbie Dolls;clothes from H&#38;M;kiddie accessories(necklace;earrings;hair clips;hair band;bags)or you can ask her mom what she really like most... :0)</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2492_C4" RELC_DATE="2011-11-20 18:48:59" RELC_USERID="U353" RELC_USERNAME="ghazalz" RELC_RELEVANCE2RELQ="Good">
			<RelCText>I know most of the birthday gifts please parents rather than the birthday kid... So; if you want a real joy of the Birthday lady; go with the surabiabi and ruby :)</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2492_C5" RELC_DATE="2011-11-20 19:29:57" RELC_USERID="U6319" RELC_USERNAME="Ryan Philip" RELC_RELEVANCE2RELQ="Good">
			<RelCText>CASIO PIANO</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2492_C6" RELC_DATE="2011-11-20 19:32:04" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Dont forget to put in a iron table and a iron;;;; they are never too young to start to look after their men</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2492_C7" RELC_DATE="2011-11-20 19:34:07" RELC_USERID="U6" RELC_USERNAME="t_coffee_or_me" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>It all depends on your budget. whats your budget?</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2492_C8" RELC_DATE="2011-11-20 19:36:38" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Good">
			<RelCText>What can I possibly say about the Fetish Barbie scheduled to spank uh; hit store shelves this autumn? Only that its about time. And I have to have one. Theres a whole cadre of people who have never liked the anatomically impossible dolls squeaky-clean image; some of us even suspected there was a kinky woman inside. Now shes becoming the straight mans/lesbian version of Toms of Finland; the one-time ideal of feminine perfection is all but wielding a whip. Oh right. She already did that dressed as Catwoman Barbie . http://inventorspot.com/articles/barbie_15545</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2492_C9" RELC_DATE="2011-11-21 11:43:46" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Thanx all .....atleast i have many things in my mind .... Thank u so much all.....</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2492_C10" RELC_DATE="2011-11-21 11:49:08" RELC_USERID="U128" RELC_USERNAME="s_isale" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>board games</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2492_C11" RELC_DATE="2011-11-21 11:50:23" RELC_USERID="U114" RELC_USERNAME="GodFather." RELC_RELEVANCE2RELQ="Good">
			<RelCText>Barbie or a Fulla Doll is always a good buy!</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2493">
		<RelQuestion RELQ_ID="Q2493" RELQ_CATEGORY="Funnies" RELQ_DATE="2011-10-25 14:52:00" RELQ_USERID="U1058" RELQ_USERNAME="rubypavino">
			<RelQSubject>Happy Halloween To All...</RelQSubject>
			<RelQBody>Its Halloween again...do u celebrate it? can you share one eerie experience of yours...</RelQBody>
		</RelQuestion>
		<RelComment RELC_ID="Q2493_C1" RELC_DATE="2011-10-25 16:55:35" RELC_USERID="U5547" RELC_USERNAME="qatari" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>RubyPavino - Why? I'm a lady now..hihihi</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2493_C2" RELC_DATE="2011-10-25 17:17:58" RELC_USERID="U1058" RELC_USERNAME="rubypavino" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>i was just kiddin coz ur pic. is a child;is that u when ur still a kid?</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2493_C3" RELC_DATE="2011-10-25 18:51:08" RELC_USERID="U2116" RELC_USERNAME="marhaba7" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>This is an entirely stupid American tradition thought up by some Dickhead President of Pumpkin land who didnt know what to do with his excess of Pumpkins in his land of plenty. He sent most of his Pumpkins to Iraq and Afghanistan I heard. Bollards - stupid question for a moronic tradition!</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2493_C4" RELC_DATE="2011-10-25 19:00:32" RELC_USERID="U1058" RELC_USERNAME="rubypavino" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>whatever!!!!</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2493_C5" RELC_DATE="2011-10-25 19:12:05" RELC_USERID="U74" RELC_USERNAME="FlyingAce" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>LOL.... marhaba7</RelCText>
		</RelComment>
		<RelComment RELC_ID="Q2493_C6" RELC_DATE="2011-10-26 02:03:21" RELC_USERID="U789" RELC_USERNAME="Vegas" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>treat...</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q2494">
		<RelQuestion RELQ_ID="Q2494" RELQ_CATEGORY="Cars" RELQ_DATE="2009-09-09 21:53:47" RELQ_USERID="U8918" RELQ_USERNAME="akino">
			<RelQSubject>transfer of car registration</RelQSubject>
			<RelQBody>hello everyone; is the any papers required for transfering of the car registration; Can any one help me on this</RelQBody>
		</RelQuestion>